apiVersion: apps/v1
kind: Deployment
metadata:
  name: gloan
spec:
  selector:
    matchLabels:
      app: gloan
  template:
    metadata:
      labels:
        app: gloan
    spec:
      containers:
        - name: gloan
          image: gloan
          ports:
            - containerPort: 8080