apiVersion: v1
kind: Service
metadata:
  name: gloan
  namespace: default
  labels:
    app: gloan
spec:
  selector:
    app: gloan
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer